// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpc/grpc.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ip2Mac_Request struct {
	RemoteAddr           string   `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserIp               string   `protobuf:"bytes,3,opt,name=user_ip,json=userIp,proto3" json:"user_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ip2Mac_Request) Reset()         { *m = Ip2Mac_Request{} }
func (m *Ip2Mac_Request) String() string { return proto.CompactTextString(m) }
func (*Ip2Mac_Request) ProtoMessage()    {}
func (*Ip2Mac_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_816d45400bc309e9, []int{0}
}

func (m *Ip2Mac_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ip2Mac_Request.Unmarshal(m, b)
}
func (m *Ip2Mac_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ip2Mac_Request.Marshal(b, m, deterministic)
}
func (m *Ip2Mac_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ip2Mac_Request.Merge(m, src)
}
func (m *Ip2Mac_Request) XXX_Size() int {
	return xxx_messageInfo_Ip2Mac_Request.Size(m)
}
func (m *Ip2Mac_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Ip2Mac_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Ip2Mac_Request proto.InternalMessageInfo

func (m *Ip2Mac_Request) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Ip2Mac_Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Ip2Mac_Request) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

type Mac2Ip_Request struct {
	RemoteAddr           string   `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mac                  string   `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mac2Ip_Request) Reset()         { *m = Mac2Ip_Request{} }
func (m *Mac2Ip_Request) String() string { return proto.CompactTextString(m) }
func (*Mac2Ip_Request) ProtoMessage()    {}
func (*Mac2Ip_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_816d45400bc309e9, []int{1}
}

func (m *Mac2Ip_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mac2Ip_Request.Unmarshal(m, b)
}
func (m *Mac2Ip_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mac2Ip_Request.Marshal(b, m, deterministic)
}
func (m *Mac2Ip_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mac2Ip_Request.Merge(m, src)
}
func (m *Mac2Ip_Request) XXX_Size() int {
	return xxx_messageInfo_Mac2Ip_Request.Size(m)
}
func (m *Mac2Ip_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Mac2Ip_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Mac2Ip_Request proto.InternalMessageInfo

func (m *Mac2Ip_Request) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Mac2Ip_Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Mac2Ip_Request) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type Response struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac                  string   `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_816d45400bc309e9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Response) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func init() {
	proto.RegisterType((*Ip2Mac_Request)(nil), "Ip2Mac_Request")
	proto.RegisterType((*Mac2Ip_Request)(nil), "Mac2Ip_Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("api/grpc/grpc.proto", fileDescriptor_816d45400bc309e9) }

var fileDescriptor_816d45400bc309e9 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x3f, 0x4b, 0xc5, 0x30,
	0x14, 0xc5, 0x7d, 0x79, 0x50, 0xdf, 0xbb, 0x42, 0x2b, 0x71, 0xb0, 0x74, 0x51, 0x32, 0x88, 0x83,
	0x44, 0xa8, 0x9f, 0xc0, 0xb1, 0x43, 0x97, 0xcc, 0x42, 0x88, 0x49, 0x94, 0x20, 0x35, 0xd7, 0xa4,
	0xc1, 0xaf, 0x2f, 0x4d, 0xff, 0x40, 0x77, 0x97, 0x90, 0x7b, 0xef, 0x8f, 0x73, 0x38, 0x07, 0x6e,
	0x14, 0xba, 0xe7, 0xcf, 0x80, 0x3a, 0x3f, 0x1c, 0x83, 0x1f, 0x3d, 0xfb, 0x80, 0xb2, 0xc3, 0xb6,
	0x57, 0x5a, 0x0a, 0xfb, 0x93, 0x6c, 0x1c, 0xe9, 0x1d, 0x5c, 0x05, 0x3b, 0xf8, 0xd1, 0x4a, 0x65,
	0x4c, 0xa8, 0x0f, 0xf7, 0x87, 0xc7, 0xb3, 0x80, 0x79, 0xf5, 0x6a, 0x4c, 0xa0, 0x0d, 0x9c, 0x50,
	0xc5, 0xf8, 0xeb, 0x83, 0xa9, 0x49, 0xbe, 0x6e, 0x33, 0xbd, 0x85, 0xcb, 0x14, 0x6d, 0x90, 0x0e,
	0xeb, 0x63, 0x3e, 0x15, 0xd3, 0xd8, 0x21, 0x93, 0x50, 0xf6, 0x4a, 0xb7, 0x1d, 0xfe, 0x8f, 0xcf,
	0x35, 0x1c, 0x07, 0xa5, 0x17, 0x8f, 0xe9, 0xcb, 0x9e, 0xe0, 0x24, 0x6c, 0x44, 0xff, 0x1d, 0x2d,
	0x2d, 0x81, 0x38, 0x5c, 0x14, 0x89, 0xc3, 0x95, 0x26, 0x1b, 0xdd, 0xbe, 0x01, 0x88, 0xa4, 0xbf,
	0x52, 0x94, 0x0a, 0x1d, 0x7d, 0x80, 0x62, 0x2e, 0x81, 0x56, 0x7c, 0xdf, 0x46, 0x73, 0xe6, 0xab,
	0x2a, 0xbb, 0x98, 0xb8, 0x39, 0x04, 0xad, 0xf8, 0x3e, 0xcd, 0x8e, 0x7b, 0x2f, 0x72, 0xb7, 0x2f,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xf8, 0xc4, 0x08, 0x72, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretApiClient is the client API for SecretApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretApiClient interface {
	Ip2Mac(ctx context.Context, in *Ip2Mac_Request, opts ...grpc.CallOption) (*Response, error)
	Mac2Ip(ctx context.Context, in *Mac2Ip_Request, opts ...grpc.CallOption) (*Response, error)
}

type secretApiClient struct {
	cc *grpc.ClientConn
}

func NewSecretApiClient(cc *grpc.ClientConn) SecretApiClient {
	return &secretApiClient{cc}
}

func (c *secretApiClient) Ip2Mac(ctx context.Context, in *Ip2Mac_Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Secret_api/Ip2Mac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretApiClient) Mac2Ip(ctx context.Context, in *Mac2Ip_Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Secret_api/Mac2Ip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretApiServer is the server API for SecretApi service.
type SecretApiServer interface {
	Ip2Mac(context.Context, *Ip2Mac_Request) (*Response, error)
	Mac2Ip(context.Context, *Mac2Ip_Request) (*Response, error)
}

// UnimplementedSecretApiServer can be embedded to have forward compatible implementations.
type UnimplementedSecretApiServer struct {
}

func (*UnimplementedSecretApiServer) Ip2Mac(ctx context.Context, req *Ip2Mac_Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ip2Mac not implemented")
}
func (*UnimplementedSecretApiServer) Mac2Ip(ctx context.Context, req *Mac2Ip_Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mac2Ip not implemented")
}

func RegisterSecretApiServer(s *grpc.Server, srv SecretApiServer) {
	s.RegisterService(&_SecretApi_serviceDesc, srv)
}

func _SecretApi_Ip2Mac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ip2Mac_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretApiServer).Ip2Mac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Secret_api/Ip2Mac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretApiServer).Ip2Mac(ctx, req.(*Ip2Mac_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretApi_Mac2Ip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mac2Ip_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretApiServer).Mac2Ip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Secret_api/Mac2Ip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretApiServer).Mac2Ip(ctx, req.(*Mac2Ip_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Secret_api",
	HandlerType: (*SecretApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ip2Mac",
			Handler:    _SecretApi_Ip2Mac_Handler,
		},
		{
			MethodName: "Mac2Ip",
			Handler:    _SecretApi_Mac2Ip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/grpc.proto",
}
